x-common-config: &common-config
  network_mode: host
  ipc: host
  environment:
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    - ROBOT_MODEL_NAME=${ROBOT_MODEL_NAME:-panther}
    - ROBOT_NAMESPACE=${ROBOT_NAMESPACE:-${ROBOT_MODEL_NAME:-panther}}
    - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}

x-cpu-config: &cpu-config
  env_file: .env.cpu

x-gpu-config: &gpu-config
  runtime: nvidia
  env_file: .env.gpu

services:
  husarion_ugv_gazebo:
    image: husarion/husarion-ugv-gazebo:jazzy-2.3.1-20250701
    container_name: husarion_ugv_gazebo
    <<:
      - *common-config
      - *gpu-config
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      ros2 launch husarion_ugv_gazebo simulation.launch.py
